### ISSUE TITLE
'module' object has no attribute 'resource'

### ISSUE THREAD

**Issue by nskitch** [mixja/boto3-session-cache#3]
Hi, 

My boto3 script makes use of both client and resource. 

`    ec2_clientr = boto3_session_cache.resource('ec2',region_name=aws_region)
AttributeError: 'module' object has no attribute 'resource'`

Is resource supported or plans to support in the future?

**Comment by mixja** [comment]
You can create a resource from the session object, but I have added support for resource in [1.0.2](https://github.com/mixja/boto3-session-cache/releases/tag/1.0.2)
